functionality:
  name: "from_bdrhap_to_h5mu"
  namespace: "convert"
  version: "main_build"
  authors:
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  inputs: []
  outputs: []
  arguments: []
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "string"
      name: "--id"
      alternatives: []
      description: "A sample ID."
      example:
      - "my_id"
      default: []
      required: true
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--input"
      alternatives:
      - "-i"
      description: "The output of a BD Rhapsody workflow."
      example:
      - "input_dir"
      default: []
      must_exist: false
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output"
      alternatives:
      - "-o"
      description: "Output h5mu file."
      example:
      - "output.h5mu"
      default: []
      must_exist: false
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "r_script"
    path: "script.R"
    is_executable: true
  description: "Convert the output of a BD Rhapsody WTA pipeline to a MuData h5 file.\n"
  test_resources:
  - type: "python_script"
    path: "run_test.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/bdrhap_5kjrt/processed/WTA.bd_rhapsody.output_raw"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms: []
info:
  config: "src/convert/from_bdrhap_to_h5mu/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/convert/from_bdrhap_to_h5mu"
  executable: "target/docker/convert/from_bdrhap_to_h5mu/from_bdrhap_to_h5mu"
  viash_version: "0.6.3"
  git_commit: "2294e349c414e49bf6bfd282c2a818aae4dbea9c"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
