functionality:
  name: "bd_rhapsody_wta"
  namespace: "ingestion"
  description: "Processing unimodal multi-sample RNA transcriptomics data."
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--input"
      required: true
      type: file
      description: One or more fastq paths, separated with semicolons.
      example: file.fastq
      multiple: true
      multiple_sep: ","
    - name: "--reference_genome"
      required: true
      type: file
      description: A path to STAR index as a tar.gz file.
      example: reference.tar.gz
    - name: "--transcriptome_annotation"
      required: true
      type: file
      description: A path to GTF annotation file.
      example: transcriptome.gtf
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf