functionality:
  name: "bd_rhapsody_extracth5ad"
  namespace: "mapping"
  version: "dev"
  description: |
    Create a h5ad file from BD Rhapsody output.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      description: Folder containing the output of the BD Rhapsody workflow.
      required: true
      example: input_dir/
    - name: "--output"
      alternatives: [-o]
      description: "Output h5ad file"
      required: true
      type: file
      direction: output
      example: output.h5ad
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: dataintuitive/randpy:py3.8
    setup:
      - type: python
        packages: [ scanpy, scipy, anndata ]
  - type: nextflow
