functionality:
  name: "bd_rhapsody_extracth5ad"
  namespace: "mapping"
  version: "dev"
  description: |
    Create a h5ad file from BD Rhapsody output.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      description: One or more folders containing the output of the BD Rhapsody workflow. If multiple are given, they are all combined into one h5ad file.
      multiple: true
      required: true
      example: input_dir/
    - name: "--output"
      alternatives: [-o]
      description: "Output h5ad file."
      required: true
      type: file
      direction: output
      example: output.h5ad
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
  - type: nextflow
