functionality:
  name: "merge"
  namespace: "dataflow"
  version: "main_build"
  authors:
  - name: "Dries Schaumont"
    email: "dries@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "DriesSchaumont"
      orcid: "0000-0002-4389-0440"
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Paths to the single-modality .h5mu files that need to be combined"
    example: []
    default:
    - "sample_paths"
    must_exist: false
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ","
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Path to the output file."
    example: []
    default:
    - "output.h5mu"
    must_exist: false
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--compression"
    alternatives: []
    description: "The compression format to be used on the final h5mu object."
    example: []
    default:
    - "gzip"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "python_script"
    path: "./script.py"
    is_executable: true
  description: "Combine one or more single-modality .h5mu files together into one\
    \ .h5mu file.\n"
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/merge_test_data/pbmc_1k_protein_v3_filtered_feature_bc_matrix_rna.h5mu"
  - type: "file"
    path: "../../../resources_test/merge_test_data/pbmc_1k_protein_v3_filtered_feature_bc_matrix_prot.h5mu"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms: []
info:
  config: "src/dataflow/merge/config.vsh.yml"
  platform: "docker"
  output: "target/docker/dataflow/merge"
  executable: "target/docker/dataflow/merge/merge"
  viash_version: "0.6.3"
  git_commit: "f7642808416809dd6e5bacf0266321aeade1d834"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
