apiVersion: v1
kind: Pod
metadata:
  labels:
    role: agent
  name: jenkins-slave
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: false
  namespace: jenkins-operator
spec:
  serviceAccount: jenkins-agent
  imagePullSecrets:
  - name: itx-aiv-artifactory
  containers:
  - name: jnlp
    image: itx-aiv.artifactrepo.jnj.com/jenkins/inbound-agent:4.10-2
    args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
  - name: agent
    image: itx-aiv.artifactrepo.jnj.com/jenkins-agent:v4.0.2
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: 2500m
        memory: 2000Mi
      requests:
        cpu: 2000m
        memory: 1700Mi
    volumeMounts:
    - mountPath: /var/docker
      name: docker
      readOnly: true
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - mkdir /root/.docker && ln -sf /var/docker/.dockerconfigjson /root/.docker/config.json
  volumes:
  - name: docker
    secret:
      secretName: itx-aiv-artifactory
