functionality:
  name: "from_cellranger_multi_to_h5mu"
  namespace: "convert"
  version: "main_build"
  authors:
  - name: "Dries Schaumont"
    email: "dries@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "DriesSchaumont"
      orcid: "0000-0002-4389-0440"
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Input folder. Must contain the output from a cellranger multi run."
    example:
    - "input_dir_containing_modalities"
    default: []
    must_exist: false
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Output h5mu file."
    example:
    - "output.h5mu"
    default: []
    must_exist: false
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--uns_metrics"
    alternatives: []
    description: "Name of the .uns slot under which to QC metrics (if any)."
    example: []
    default:
    - "metrics_cellranger"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Converts the output from cellranger multi to a single .h5mu file.\n\
    \nCurrently does not allow parsing the output from cell barcode demultiplexing.\n"
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/10x_5k_anticmv"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms: []
info:
  config: "src/convert/from_cellranger_multi_to_h5mu/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/convert/from_cellranger_multi_to_h5mu"
  executable: "target/docker/convert/from_cellranger_multi_to_h5mu/from_cellranger_multi_to_h5mu"
  viash_version: "0.6.3"
  git_commit: "2387febab0284e4eb6b607d96f08fbf8b44f4c74"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
