functionality:
  name: "scvi"
  namespace: "integrate"
  version: "main_build"
  authors:
  - name: "Malte D. Luecken"
    roles:
    - "author"
    info:
      role: "Core Team Member"
      links:
        email: "malte.luecken@helmholtz-muenchen.de"
        github: "LuckyMD"
        orcid: "0000-0001-7464-7921"
        linkedin: "malte-l%C3%BCcken-b8b21049"
        twitter: "MDLuecken"
      organizations:
      - name: "Helmholtz Munich"
        href: "https://www.helmholtz-munich.de"
        role: "Group Leader"
      - name: "Open Problems"
        href: "https://openproblems.bio"
        role: "Core Member"
  - name: "Dries Schaumont"
    roles:
    - "maintainer"
    info:
      role: "Core Team Member"
      links:
        email: "dries@data-intuitive.com"
        github: "DriesSchaumont"
        orcid: "0000-0002-4389-0440"
        linkedin: "dries-schaumont"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Data Scientist"
  - name: "Matthias Beyens"
    roles:
    - "contributor"
    info:
      role: "Contributor"
      links:
        github: "MatthiasBeyens"
        orcid: "0000-0003-3304-0706"
        email: "matthias.beyens@gmail.com"
        linkedin: "mbeyens"
      organizations:
      - name: "Janssen Pharmaceuticals"
        href: "https://www.janssen.com"
        role: "Principal Scientist"
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "file"
      name: "--input"
      alternatives:
      - "-i"
      description: "Input h5mu file"
      info: null
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--modality"
      info: null
      default:
      - "rna"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--input_layer"
      description: "Input layer to use. If None, X is used"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_batch"
      description: "Column name discriminating between your batches."
      info: null
      default:
      - "sample_id"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--var_input"
      description: ".var column containing highly variable genes. By default, do not\
        \ subset genes."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output"
      alternatives:
      - "-o"
      description: "Output h5mu file."
      info: null
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--model_output"
      description: "Folder where the state of the trained model will be saved to."
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_compression"
      description: "The compression format to be used on the output h5mu object."
      info: null
      example:
      - "gzip"
      required: false
      choices:
      - "gzip"
      - "lzf"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obsm_output"
      description: "In which .obsm slot to store the resulting integrated embedding."
      info: null
      default:
      - "X_scvi_integrated"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Early stopping arguments"
    arguments:
    - type: "boolean"
      name: "--early_stopping"
      description: "Whether to perform early stopping with respect to the validation\
        \ set."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--early_stopping_monitor"
      description: "Metric logged during validation set epoch."
      info: null
      default:
      - "elbo_validation"
      required: false
      choices:
      - "elbo_validation"
      - "reconstruction_loss_validation"
      - "kl_local_validation"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--early_stopping_patience"
      description: "Number of validation epochs with no improvement after which training\
        \ will be stopped."
      info: null
      default:
      - 45
      required: false
      min: 1
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--early_stopping_min_delta"
      description: "Minimum change in the monitored quantity to qualify as an improvement,\
        \ i.e. an absolute change of less than min_delta, will count as no improvement."
      info: null
      default:
      - 0.0
      required: false
      min: 0.0
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Learning parameters"
    arguments:
    - type: "integer"
      name: "--max_epochs"
      description: "Number of passes through the dataset, defaults to (20000 / number\
        \ of cells) * 400 or 400; whichever is smallest."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--reduce_lr_on_plateau"
      description: "Whether to monitor validation loss and reduce learning rate when\
        \ validation set `lr_scheduler_metric` plateaus."
      info: null
      default:
      - true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--lr_factor"
      description: "Factor to reduce learning rate."
      info: null
      default:
      - 0.6
      required: false
      min: 0.0
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--lr_patience"
      description: "Number of epochs with no improvement after which learning rate\
        \ will be reduced."
      info: null
      default:
      - 30.0
      required: false
      min: 0.0
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Data validition"
    arguments:
    - type: "integer"
      name: "--n_obs_min_count"
      description: "Minimum number of cells threshold ensuring that every obs_batch\
        \ category has sufficient observations (cells) for model training."
      info: null
      default:
      - 0
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--n_var_min_count"
      description: "Minimum number of genes threshold ensuring that every var_input\
        \ filter has sufficient observations (genes) for model training."
      info: null
      default:
      - 0
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "../../utils/subset_vars.py"
  description: "Performs scvi integration as done in the human lung cell atlas https://github.com/LungCellAtlas/HLCA"
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "../../utils/subset_vars.py"
  - type: "file"
    path: "../../../resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_mms.h5mu"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "nvcr.io/nvidia/pytorch:23.05-py3"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "apt"
    packages:
    - "libpng-dev"
    - "libjpeg-dev"
    interactive: false
  - type: "docker"
    run:
    - "pip install \"jax[cuda]\" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html\n"
  - type: "python"
    user: false
    packages:
    - "mudata~=0.2.0"
    - "anndata~=0.8.0"
    - "scanpy~=1.9.2"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "scvi-tools~=1.0.0"
    upgrade: false
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    label:
    - "gpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/integrate/scvi/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/integrate/scvi"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/integrate/scvi/scvi"
  viash_version: "0.7.4"
  git_commit: "f32fe83de802a205ec8893add69084e8cfdef645"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
