functionality:
  name: "add_id"
  namespace: "metadata"
  version: "main_build"
  authors:
  - name: "Dries Schaumont"
    email: "dries@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "DriesSchaumont"
      orcid: "0000-0002-4389-0440"
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Path to the input .h5mu."
    example:
    - "sample_path"
    default: []
    must_exist: false
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--input_id"
    alternatives: []
    description: "The input id."
    example: []
    default: []
    required: true
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--obs_output"
    alternatives: []
    description: "Name of the .obs column where to store the id."
    example: []
    default:
    - "sample_id"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    example:
    - "output.h5mu"
    default: []
    must_exist: false
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean_true"
    name: "--make_observation_keys_unique"
    alternatives: []
    description: "Join the id to the .obs index (.obs_names)."
    direction: "input"
    dest: "par"
  argument_groups: []
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Add id of .obs. Also allows to make .obs_names (the .obs index) unique\
    \ \nby prefixing the values with an unique id per .h5mu file.\n"
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/concat_test_data/e18_mouse_brain_fresh_5k_filtered_feature_bc_matrix_subset_unique_obs.h5mu"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms: []
info:
  config: "src/metadata/add_id/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/metadata/add_id"
  executable: "target/docker/metadata/add_id/add_id"
  viash_version: "0.6.3"
  git_commit: "b619db0435bcb6fcdc7c9d7f6c22a55212989459"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
