functionality:
  name: "from_bd_to_10x_molecular_barcode_tags"
  namespace: "convert"
  version: "main_build"
  authors:
  - name: "Dries Schaumont"
    email: "dries@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "DriesSchaumont"
      orcid: "0000-0002-4389-0440"
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Input SAM or BAM file."
    example:
    - "input.bam"
    default: []
    must_exist: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Output alignment file."
    example:
    - "output.sam"
    default: []
    must_exist: false
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean_true"
    name: "--bam"
    alternatives: []
    description: "Output a BAM file."
    direction: "input"
    dest: "par"
  - type: "integer"
    name: "--threads"
    alternatives:
    - "-t"
    description: "Number of threads"
    example: []
    default: []
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Convert the molecular barcode sequence SAM tag from BD format (MA)\
    \ to 10X format (UB).\n"
  test_resources:
  - type: "bash_script"
    path: "run_test.sh"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/bdrhap_5kjrt/processed/WTA.bd_rhapsody.output_raw"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms: []
info:
  config: "src/convert/from_bd_to_10x_molecular_barcode_tags/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/convert/from_bd_to_10x_molecular_barcode_tags"
  executable: "target/docker/convert/from_bd_to_10x_molecular_barcode_tags/from_bd_to_10x_molecular_barcode_tags"
  viash_version: "0.6.3"
  git_commit: "fcb1bd2a0f76d2dd992272b45d76a89e8cf3e0d3"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
