functionality:
  name: "cellranger_count"
  namespace: "mapping"
  version: "dev"
  description: |
    Use Cellranger to count gene expression (targeted or whole-transcriptome) and/or 
    feature barcode reads from a single sample and GEM well.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      type: file
      direction: input
      description: Path of folder created by mkfastq or bcl2fastq
      example: fastq_dir
    - name: "--id"
      type: string
      default: cr
      description: Output folder for the count files.
    - name: "--libraries"
      type: file
      description: File containing the library definitions
      required: false
    - name: "--feature_ref"
      type: file
      description: File containing the barcode info
      required: false
    - name: "--transcriptome"
      type: file
      direction: input
      description: Path of folder containing 10x-compatible reference.
      required: true
      example: reference_dir
    - name: "--output"
      required: true
      type: file
      direction: output
      description: "Path to cellranger output folder"
      example: output
    - name: "--log"
      type: string
      description: Path to the log file (stdout and stderr)
      default: log.txt
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: litd/docker-cellranger:v6.0.0
  - type: nextflow
    directives:
      label: [ highmem, highcpu ]