functionality:
  name: "from_10xmtx_to_h5mu"
  namespace: "convert"
  version: "main_build"
  authors:
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Input mtx folder"
    example:
    - "input_dir_containing_gz_files"
    default: []
    must_exist: false
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Output h5mu file."
    example:
    - "output.h5mu"
    default: []
    must_exist: false
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Converts a 10x mtx into an h5mu file.\n"
  test_resources:
  - type: "python_script"
    path: "run_test.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/pbmc_1k_protein_v3"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms: []
info:
  config: "src/convert/from_10xmtx_to_h5mu/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/convert/from_10xmtx_to_h5mu"
  executable: "target/docker/convert/from_10xmtx_to_h5mu/from_10xmtx_to_h5mu"
  viash_version: "0.6.3"
  git_commit: "b6ab28e464be2057d6bcd9fa7f76f992f58e5a9e"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
