functionality:
  name: hvg_scanpy
  namespace: "hvg"
  version: "dev"
  description: |
    Seurat flavored HVG as described by Satija, 2015.
  authors:
    - name: Dries De Maeyer
      email: ddemaeyer@gmail.com
      roles: [ maintainer ]
      props: { account: ddemaey1 }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5ad file
      direction: input
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Write the parameters to a json file.
      direction: output
    - name: "--excludedGenes"
      type: string
      description: Genes to exclude from the highly variable genes. This can be of use when performing for example analysis on B/T cells which have variable genes that should not be taken into account.
      default: ""
    - name: "--flavor"
      type: string
      description: The flavor to select for highly variable genes. Default seurat, other options seurat_v3 or cell_ranger
      default: "seurat"
  resources:
    - type: python_script
      path: ./script.py
  tests:
    - type: python_script
      path: test.py
    - path: ../../../resources/test/pbmc_1k_protein_v3_filtered_feature_bc_matrix.h5ad
platforms:
  - type: docker
    image: python:3.8
    python:
      packages:
        - scanpy
        - loompy
    workdir: /app
  - type: nextflow
