functionality:
  name: "cellranger_count_split"
  namespace: "mapping"
  version: "main_build"
  authors:
  - name: "Angela Pisco"
    roles:
    - "author"
    props:
      github: "aopisco"
      orcid: "0000-0003-0142-2355"
  - name: "Samuel D'Souza"
    roles:
    - "author"
    props:
      github: "srdsam"
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "author"
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives: []
    description: "Output directory from a Cell Ranger count run."
    example:
    - "input_dir"
    default: []
    must_exist: false
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--filtered_h5"
    alternatives: []
    example:
    - "filtered_feature_bc_matrix.h5"
    default: []
    must_exist: false
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--metrics_summary"
    alternatives: []
    example:
    - "metrics_summary.csv"
    default: []
    must_exist: false
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--molecule_info"
    alternatives: []
    example:
    - "molecule_info.h5"
    default: []
    must_exist: false
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--bam"
    alternatives: []
    example:
    - "possorted_genome_bam.bam"
    default: []
    must_exist: false
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--bai"
    alternatives: []
    example:
    - "possorted_genome_bam.bam.bai"
    default: []
    must_exist: false
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--raw_h5"
    alternatives: []
    example:
    - "raw_feature_bc_matrix.h5"
    default: []
    must_exist: false
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Split 10x Cell Ranger output directory into separate output fields."
  test_resources: []
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms: []
info:
  config: "src/mapping/cellranger_count_split/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/mapping/cellranger_count_split"
  executable: "target/docker/mapping/cellranger_count_split/cellranger_count_split"
  viash_version: "0.6.3"
  git_commit: "2387febab0284e4eb6b607d96f08fbf8b44f4c74"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
