functionality:
  name: "bd_rhapsody_wta"
  namespace: "mapping"
  version: "dev"
  description: |
    A viash component for the BD Rhapsody Analysis CWL pipeline.

    The CWL pipeline file is obtained by cloning 'https://bitbucket.org/CRSwDev/cwl/src/master/' and removing all objects with class 'DockerRequirement' from the JSON.

    The reference_genome and transcriptome_annotation files can be downloaded from these locations:
      - Human: http://bd-rhapsody-public.s3-website-us-east-1.amazonaws.com/Rhapsody-WTA/GRCh38-PhiX-gencodev29/
      - Mouse: http://bd-rhapsody-public.s3-website-us-east-1.amazonaws.com/Rhapsody-WTA/GRCm38-PhiX-gencodevM19/
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      description: Path to your read files in the FASTQ.GZ format. You may specify as many R1/R2 read pairs as you want.
      required: true
      multiple: true
      multiple_sep: ':'
    - name: "--subsample"
      type: double
      description: A number >1 or fraction (0 < n < 1) to indicate the number or percentage of reads to subsample.
    - name: "--reference_genome"
      alternatives: [-r]
      type: file
      required: true
      description: "Path to STAR index for tar.gz format."
    - name: "--transcriptome_annotation"
      alternatives: [-t]
      type: file
      description: Path to GTF annotation file
      required: true
    - name: "--output"
      alternatives: [-o]
      description: "Output folder. Output still needs to be processed further."
      required: true
      type: file
      direction: output
    - name: "--exact_cell_count"
      type: integer
      description: "Exact cell count - Set a specific number (>=1) of cells as putative, based on those with the highest error-corrected read count"
    - name: "--disable_putative_calling"
      type: boolean
      description: "Disable Refined Putative Cell Calling - Determine putative cells using only the basic algorithm (minimum second derivative along the cumulative reads curve). The refined algorithm attempts to remove false positives and recover false negatives, but may not be ideal for certain complex mixtures of cell types. Does not apply if Exact Cell Count is set."
    # Comment by Robrecht: Nxf viash modules don't support optional files yet.
    # - name: "--abseq_reference"
    #   alternatives: [-a]
    #   type: file
    #   description: Path to the AbSeq reference file in FASTA format. Only needed if BD AbSeq Ab-Oligos are used.
    #   multiple: true
    #   multiple_sep: ':'
    # - name: "--supplemental_reference"
    #   alternatives: [-s]
    #   type: file
    #   description: Path to the supplemental reference file in FASTA format. Only needed if there are additional transgene sequences used in the experiment.
    #   multiple: true
    #   multiple_sep: ':'
  resources:
    - type: bash_script
      path: ./script.sh
    - path: rhapsody_wta_1.9.1_nodocker.cwl
  # Comment by Robrecht: I'm trying to create smaller references, but I didn't manage to create one which works with the Rhapsody pipeline
  # tests:
  #   - type: bash_script
  #     path: test/run_test.sh
  #   - path: http://bd-rhapsody-public.s3.amazonaws.com/Rhapsody-WTA-test-data/sample_R1_.fastq.gz # 100MB
  #   - path: http://bd-rhapsody-public.s3.amazonaws.com/Rhapsody-WTA-test-data/sample_R2_.fastq.gz # 150MB
  #   - path: http://bd-rhapsody-public.s3.amazonaws.com/Rhapsody-WTA/GRCh38-PhiX-gencodev29/GRCh38-PhiX-gencodev29-20181205.tar.gz # 29GB
  #   - path: http://bd-rhapsody-public.s3.amazonaws.com/Rhapsody-WTA/GRCh38-PhiX-gencodev29/gencodev29-20181205.gtf # 1.1GB
platforms:
  - type: docker
    image: bdgenomics/rhapsody:1.9.1
    setup:
      - type: apt
        packages:
          - cwltool
  - type: nextflow
