functionality:
  name: "run_cirrocumulus"
  namespace: "interactive"
  version: "main_build"
  authors: []
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Directory to mount"
    example: []
    default:
    - "."
    must_exist: false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--port"
    alternatives:
    - "-p"
    description: "Port to use"
    example: []
    default:
    - "5005"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: ""
  test_resources: []
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms: []
info:
  config: "src/interactive/run_cirrocumulus/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/interactive/run_cirrocumulus"
  executable: "target/docker/interactive/run_cirrocumulus/run_cirrocumulus"
  viash_version: "0.6.3"
  git_commit: "a3ba5a1481f9cd105ae211003a3e291b406c35fe"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
