functionality:
  name: spaceranger_count
  namespace: mapping
  description: Align fastq files using spaceranger count.
  authors:
    - __merge__: ../../authors/samuel_d_souza.yaml
      roles: [ author ]
  arguments:
    - type: file
      name: --input
      required: true
      example: 'path/to/fastqs'
      description: The fastq.gz files to align. Can also be a single directory containing fastq.gz files.
    - type: file
      name: --reference
      required: true
      description: The path to the spaceranger reference tar.gz file. Can also be a directory.
      example: reference.tar.gz
    - type: file
      name: --image
      required: true
      description: The corresponding capture area image in either TIFF, QPTIFF or JPEG format. If dark background fluorescence or composite colored fluorescence image, use --image_type.
      example: sample345.tiff
    - type: string
      name: --slide
      required: false
      description: Visium slide serial number. Required unless --unknown-slide is passed.
      example: V19J01-123
    - type: string
      name: --area
      required: false
      description: Visium capture area identifier. Required unless --unknown-slide is passed. Options for Visium are A1, B1, C1, D1.
      example: A1
    - type: file
      name: --slidefile
      required: false
      description: Slide layout file indicating capture spot and fiducial spot positions. Required when no internet access unless --unknown-slide is passed.
      example: V19J01-123.gpr
    - type: string
      name: --unknown_slide
      required: false
      description: Set this if the slide serial number and area identifier are unknown. The value passed to this depends on the slide version. Setting this will cause Space Ranger to use default spot positions. Not compatible with --slide, --area, or --slidefile.
      example: visium-1
    - type: file
      name: --output
      direction: output
      description: The folder to store the alignment results.
      example: "/path/to/output"
      required: true
    - type: string
      name: --image_type
      example: "darkimage" or "colorizedimage"
      description: Type of capture area image.
    - type: boolean
      name: "--reorient-images"
      default: true
      description: Whether the pipeline should rotate and mirror the image to align the upright hourglass fiducial pattern in the top left corner.
    - type: boolean
      name: "--no-bam"
      default: false
      description: Whether to generate a BAM file.
    - type: boolean
      name: "--nosecondary"
      default: false
      description: Disable secondary analysis, such as dimensionality reduction, clustering, spatial enrichment calculation (Moran's I) and visualization.
  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/spaceranger_tiny_fastq
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/spaceranger:1.3
    setup:
      - type: docker
        run: apt update && apt upgrade -y
  - type: nextflow
    directives:
      label: [ highmem, highcpu ]