functionality:
  name: "cellxgene_census"
  namespace: "query"
  version: "main_build"
  authors:
  - name: "Matthias Beyens"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        github: "MatthiasBeyens"
        orcid: "0000-0003-3304-0706"
        email: "matthias.beyens@gmail.com"
        linkedin: "mbeyens"
      organizations:
      - name: "Janssen Pharmaceuticals"
        href: "https://www.janssen.com"
        role: "Principal Scientist"
  argument_groups:
  - name: "Inputs"
    description: "Arguments related to the input (aka query) dataset."
    arguments:
    - type: "string"
      name: "--input_database"
      description: "Full input database S3 prefix URL. Default: CellxGene Census"
      info: null
      example:
      - "s3://"
      default:
      - "CellxGene"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--modality"
      description: "Which modality to store the output in."
      info: null
      default:
      - "rna"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--cellxgene_release"
      description: "CellxGene Census release date. More information: https://chanzuckerberg.github.io/cellxgene-census/cellxgene_census_docsite_data_release_info.html"
      info: null
      default:
      - "2023-05-15"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Query"
    description: "Arguments related to the query."
    arguments:
    - type: "string"
      name: "--species"
      description: "Specie(s) of interest. If not specified, Homo Sapiens will be\
        \ queried."
      info: null
      example:
      - "homo_sapiens"
      default:
      - "homo_sapiens"
      required: false
      choices:
      - "homo_sapiens"
      - "mus_musculus"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--cell_type"
      description: "Cell type(s) of interest. Cell type should be one of the Cell\
        \ Ontology terms. If not specified, all cell types will be queried."
      info: null
      example:
      - "mesothelial fibroblast"
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--tissue"
      description: "Tissue(s) of interest. If not specified, all tissues will be queried."
      info: null
      example:
      - "lung"
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--technology"
      description: "Technology(ies) of interest. If not specified, all technologies\
        \ will be queried."
      info: null
      example:
      - "10x 3' v3"
      required: false
      choices:
      - "10x 3' v1"
      - "10x 3' v2"
      - "10x 3' v3"
      - "10x 5' v1"
      - "10x 5' v2"
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--suspension"
      description: "Suspension(s) of interest. If not specified, all suspensions will\
        \ be queried."
      info: null
      example:
      - "cell"
      required: false
      choices:
      - "cell"
      - "nucleus"
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--is_primary_data"
      description: "Allow only primary data in the query in order to prevent of data\
        \ duplication."
      info: null
      default:
      - true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_column_names"
      description: "obs columns of interest. If not specified, all columns will be\
        \ returned."
      info: null
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--metadata_only"
      description: "By default only returns metadata of obs layer of query. If False,\
        \ returns metadata of obs layer and gene expression matrix of query"
      info: null
      default:
      - true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    description: "Output arguments."
    arguments:
    - type: "file"
      name: "--output"
      description: "Output h5mu file."
      info: null
      example:
      - "output.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_compression"
      info: null
      example:
      - "gzip"
      required: false
      choices:
      - "gzip"
      - "lzf"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "./cl-base.obo"
  description: "Query CellxGene Census or user-specified TileDBSoma object, and eventually\
    \ fetch cell and gene metadata or/and expression counts."
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.9"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "python"
    user: false
    packages:
    - "mudata~=0.2.3"
    - "anndata~=0.9.1"
    - "cellxgene-census~=1.2.0"
    - "obonet~=1.0.0"
    upgrade: true
  test_setup:
  - type: "python"
    user: false
    packages:
    - "viashpy"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "highmem"
    - "singlecpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/query/cellxgene_census/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/query/cellxgene_census"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/query/cellxgene_census/cellxgene_census"
  viash_version: "0.7.5"
  git_commit: "77f8c2679c72268b2ffad0c4f2c62db18b553205"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
