functionality:
  name: freemuxlet
  namespace: deconvolution
  description: |
    Runs the freemuxlet demultiplexing tool for converting.
  authors:
    - name: Dries De Maeyer
      roles: [ author, maintainer ]
      props: { github: ddemaeyer }
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      description: Bam file that contains the mapped cells to be demultiplexed.
      example: bam_file.bam
    - name: "--vcf"
      alternatives: [ "-s" ]
      type: file
      required: true
      description: VCF file containing the reference locations for assigning individual to cell ids.
      example: vcf_file.vcf
    - name: "--sampleOutputFile"
      alternatives: [ "-o" ]
      type: file
      direction: output
      required: true
      description: Output file containing the sample identities
      example: output_clustering_file.gz
    - name: "--vcfOutputFile"
      type: file
      direction: output
      required: true
      description: Output file containing variants associated with the sample identities.
      example: output_vcf.vcf.gz
    - name: "--numberOfSamples"
      type: integer
      direction: input
      required: true
      description: Number of samples to demultiplex to.
      example: 4
  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
    - path: ../../../resources_test/demuxafy_test_data/
platforms:
  - type: docker
    image: vibsinglecellnf/popscle
  - type: nextflow
    variant: vdsl3
    directives:
      label: [ midmem, midcpu ]
