functionality:
  name: "build_cellranger_reference"
  namespace: "reference"
  version: "main_build"
  authors:
  - name: "Angela Pisco"
    roles:
    - "author"
    props:
      github: "aopisco"
      orcid: "0000-0003-0142-2355"
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "author"
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--genome_fasta"
    alternatives: []
    description: "Reference genome fasta."
    example:
    - "genome_sequence.fa.gz"
    default: []
    must_exist: false
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcriptome_gtf"
    alternatives: []
    description: "Reference transcriptome annotation."
    example:
    - "transcriptome_annotation.gtf.gz"
    default: []
    must_exist: false
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives: []
    description: "Output folder"
    example:
    - "cellranger_reference"
    default: []
    must_exist: false
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Build a Cell Ranger-compatible reference folder from user-supplied\
    \ genome FASTA and gene GTF files. Creates a new folder named after the genome."
  test_resources: []
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms: []
info:
  config: "src/reference/build_cellranger_reference/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/reference/build_cellranger_reference"
  executable: "target/docker/reference/build_cellranger_reference/build_cellranger_reference"
  viash_version: "0.6.3"
  git_commit: "c4c8e93cd71b9e44cdc4a1425df00971ce8e8073"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
