functionality:
  name: "from_h5mu_to_seurat"
  namespace: "convert"
  version: "dev"
  description: |
    Converts an h5mu file into a Seurat file.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5mu file
      direction: input
      required: true
      example: input.h5mu
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output Seurat file
      direction: output
      required: true
      example: output.rds
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: r_script
      path: run_test.R
    - path: ../../../resources_test/pbmc_1k_protein_v3
platforms:
  - type: docker
    image: eddelbuettel/r2u:22.04
    setup:
      - type: apt
        packages: 
          - libhdf5-dev
          - libgeos-dev
          - python3
          - python3-pip
          - python-is-python3
      - type: python
        pip: [ scanpy, anndata<0.8 ]
      - type: r
        cran: [ anndata, hdf5r, testthat ]
      - type: r
        github: pmbio/MuDataSeurat
  - type: nextflow
    variant: vdsl3
