functionality:
  name: umap
  namespace: "projection"
  version: "dev"
  description: "UMAP(Uniform Manifold Approximation and Projection) is a novel manifold learning technique for dimension reduction. UMAP is constructed from a theoretical framework based in Riemannian geometry and algebraic topology. The result is a practical scalable algorithm that applies to real world data. The UMAP algorithm is competitive with t-SNE for visualization quality, and arguably preserves more of the global structure with superior run time performance. Furthermore, UMAP has no computational restrictions on embedding dimension, making it viable as a general purpose dimension reduction technique for machine learning. \n\nFor more information about the method see https://arxiv.org/abs/1802.03426\n"
  authors:
    - name: Dries De Maeyer
      email: ddemaeyer@gmail.com
      roles: [ maintainer ]
      props: { account: ddemaey1 }
  arguments:
    - name: "--input"
      type: file
      description: Input h5ad file
      direction: input
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5ad file.
      direction: output
      required: true
    - name: "--min_dist"
      type: double
      description: The effective minimum distance between embedded points. Smaller values will result in a more clustered/clumped embedding where nearby points on the manifold are drawn closer together, while larger values will result on a more even dispersal of points. The value should be set relative to the spread value, which determines the scale at which embedded points will be spread out. The default of in the umap-learn package is 0.1.
      default: 0.5
    - name: "--alpha"
      type: double
      description: The initial learning rate for the embedding optimization.
      default: 1.0
    - name: "--gamma"
      type: double
      description: Weighting applied to negative samples in low dimensional embedding optimization. Values higher than one will result in greater weight being given to negative samples.
      default: 1.0
    - name: "--random_seed"
      type: integer
      description: Random seed for Leiden algrithm.
      default: 0
    - name: "--negative_sample_rate"
      type: integer
      description: The number of negative edge/1-simplex samples to use per positive edge/1-simplex sample in optimizing the low dimensional embedding.
      default: 5
    - name: "--init_pos"
      type: string
      description: How to initialize the low dimensional embedding. Called init in the original UMAP. Options are paga, spectral and random.
      default: "spectral"
  resources:
    - type: python_script
      path: ./script.py
  tests:
    - type: bash_script
      path: run_test.sh
    - path: ../../../resources/test/pbmc_1k_protein_v3_filtered_feature_bc_matrix.norm.hvg.pca.nn.umap.h5ad
platforms:
  - type: docker
    image: python:3.8
    python:
      packages:
        - scanpy
    workdir: /app
  - type: nextflow
    label: highcpu
