functionality:
  name: "build_bdrhap_reference"
  namespace: "reference"
  version: "main_build"
  authors:
  - name: "Angela Pisco"
    roles:
    - "author"
    props:
      github: "aopisco"
      orcid: "0000-0003-0142-2355"
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "author"
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--genome_fasta"
    alternatives: []
    description: "Reference genome fasta."
    example:
    - "genome_sequence.fa.gz"
    default: []
    must_exist: false
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcriptome_gtf"
    alternatives: []
    description: "Reference transcriptome annotation."
    example:
    - "transcriptome_annotation.gtf.gz"
    default: []
    must_exist: false
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives: []
    description: "Star index"
    example:
    - "star_index.tar.gz"
    default: []
    must_exist: false
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Compile a reference into a STAR index compatible with the BD Rhapsody\
    \ pipeline."
  test_resources: []
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms: []
info:
  config: "src/reference/build_bdrhap_reference/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/reference/build_bdrhap_reference"
  executable: "target/docker/reference/build_bdrhap_reference/build_bdrhap_reference"
  viash_version: "0.6.3"
  git_commit: "b24ccde16041184e55166b0ae005d191f193d097"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
