name: run_dependabot

on:
  workflow_dispatch:


jobs:
  list:
    runs-on: ubuntu-latest
      
    outputs:
      component_matrix: ${{ steps.set_matrix.outputs.components }}
    steps:
    - uses: actions/checkout@v3

    - uses: viash-io/viash-actions/setup@v3

    - id: ns_list_components
      uses: viash-io/viash-actions/ns-list@v3
      with:
        platform: docker
        src: src
        format: json

    - id: set_matrix
      run: |
        echo "components=$(jq -c '[ .[] | 
          { 
            "name": (.functionality.namespace + (.platforms | map(select(.type == "docker"))[0].namespace_separator) + .functionality.name),
            "config": .info.config,
            "dir": .info.config | capture("^(?<dir>.*\/)").dir
          }
        ]' ${{ steps.ns_list_components.outputs.output_file }} )" >> $GITHUB_OUTPUT

  push_documentation:
    runs-on: ubuntu-latest
    needs: [ list ]

    steps:
      - uses: actions/checkout@v3
        with:
          path: openpipelines

      - uses: actions/checkout@v3
        with:
          repository: openpipelines-bio/website
          path: website
          token: ${{ secrets.GTHB_PAT }}

      - uses: viash-io/viash-actions/setup@v3
      
      