name: integration test

on:
  workflow_dispatch:
  schedule:
    - cron: '33 2 * * *'

jobs:
  # Build and create containers
  build:
    uses: ./.github/workflows/main-build.yaml
    with:
      push_containers: true
      version: 'integration_build'
      target_tag: 'integration_build'
      deploy_to_viash_hub: 'false'
    secrets: inherit

  # Synchronize S3 Bucket and create cache for per-component runs
  sync_s3:
    env:
      s3_bucket: s3://openpipelines-data/
    runs-on: ubuntu-latest

    outputs:
      cache_key: ${{ steps.cache.outputs.cache_key }}

    steps:
    - uses: viash-io/viash-actions/project/sync-and-cache-s3@v4
      id: 'cache' 
      with:
        s3_bucket: $s3_bucket
        dest_path: resources_test
        cache_key_prefix: resources_test__

  # phase 2
  build:
    needs: [build, sync_s3] 

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.list.outputs.component_matrix) }}

    steps:
    # Remove unnecessary files to free up space. Otherwise, we get 'no space left on device.'
    - uses: data-intuitive/reclaim-the-bytes@v2
    
    - name: Keep symlinks as-is
      run: |
        git config --global core.symlinks true

    - uses: actions/checkout@v4

    - uses: viash-io/viash-actions/setup@v4

    - name: Build container
      uses: viash-io/viash-actions/ns-build@v4
      with:
        config_mod: .functionality.version := 'integration_build'
        setup: build
        src: ${{ matrix.component.dir }}
        
    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GTHB_USER }}
        password: ${{ secrets.GTHB_PAT }}

    - name: Push container
      uses: viash-io/viash-actions/ns-build@v4
      with:
        config_mod: .functionality.version := 'integration_build'
        platform: docker
        src: ${{ matrix.component.dir }}
        setup: push

  ###################################
  # phase 3
  integration_test:
    needs: [ build, list ]
    if: "${{ needs.list.outputs.workflow_matrix != '[]' }}"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.list.outputs.workflow_matrix) }}

    steps:
    # Remove unnecessary files to free up space. Otherwise, we get 'no space left on device.'
    - uses: data-intuitive/reclaim-the-bytes@v2
    
    - name: Keep symlinks as-is
      run: |
        git config --global core.symlinks true

    - uses: actions/checkout@v4

    - uses: viash-io/viash-actions/setup@v4

    - uses: nf-core/setup-nextflow@v1.4.0

    # build target dir
    # use containers from integration_build branch, hopefully these are available
    - name: Build target dir
      uses: viash-io/viash-actions/ns-build@v4
      with:
        config_mod: ".functionality.version := 'integration_build'"
        parallel: true

    # use cache
    - name: Cache resources data
      uses: actions/cache@v3
      timeout-minutes: 5
      with:
        path: resources_test
        key: ${{ needs.list.outputs.cache_key }}
        fail-on-cache-miss: true

    - name: Remove unused test resources to save space
      shell: bash
      run: |
        readarray -t resources < <(viash config view --format json "${{ matrix.component.config }}" | jq -r -c '(.info.config | capture("^(?<dir>.*\/)").dir) as $dir | .functionality.test_resources | map(select(.type == "file")) | map($dir + .path) | unique | .[]')
        to_not_remove=()
        for resource in "${resources[@]}"; do
          if [[ $resource == *"resources_test"* ]]; then
            relative_path=${resource#*resources_test/}
            relative_path_trailing_slash_removed=${relative_path%/}
            to_not_remove+=("-path" "./resources_test/$relative_path_trailing_slash_removed" "-prune" "-o")
          fi
        done
        # Remove last prune and -o
        if (( ${#errors[@]} )); then
          unset 'to_not_remove[${#to_not_remove[@]}-1]'
          unset 'to_not_remove[${#to_not_remove[@]}-1]'
          to_not_remove+=( "(" "${to_not_remove[@]}" ")" "-prune" "-o")
        fi
        find ./resources_test/ "${to_not_remove[@]}" -type f -exec rm {} +

    - name: Run integration test
      timeout-minutes: 60
      run: |
        # todo: replace with viash test command
        export NXF_VER=22.04.5
        nextflow run . \
          -main-script "${{ matrix.component.main_script }}" \
          -entry "${{ matrix.component.entry }}" \
          -profile docker,mount_temp,no_publish \
          -c src/workflows/utils/labels_ci.config
