functionality:
  name: nn
  namespace: "nn"
  version: "dev"
  description: |
    Construct a nearest neighborhood network from the input.
  authors:
    - name: Dries De Maeyer
      email: ddemaeyer@gmail.com
      roles: [ maintainer ]
      props: { account: ddemaey1 }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5ad file
      direction: input
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5ad file containing the dimred object.
      direction: output
    - name: "--metric"
      alternatives: ["-m"]
      type: string
      default: "cosine"
      description: The distance metric to be used in the generation of the nearest neighborhood network.
    - name: "--nNeighbors"
      type: integer
      default: 15
      description: The number of neighors to be present in the nn-network.
  resources:
    - type: python_script
      path: ./script.py
  tests:
    - type: bash_script
      path: run_test.sh
    - path: ../../../resources/test/pbmc_1k_protein_v3_filtered_feature_bc_matrix.h5ad
platforms:
  - type: docker
    image: python:3.8
    python:
      packages:
        - scanpy
        - loompy
  - type: nextflow
