functionality:
  name: "cellranger_demux"
  namespace: "ingestion"
  description: "Cell Ranger demux pipeline."
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--input"
      required: true
      type: file
      description: A BCL directory.
      example: /path/to/bcl
    - name: "--sample_sheet"
      required: true
      type: file
      description: The sample sheet for the samples to be demultiplexed.
      example: sample_sheet.csv
  resources:
    - type: nextflow_script
      path: main.nf
    - path: nextflow.config
  tests:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
platforms:
  - type: native